# Используем базовый образ PHP с Apache
FROM php:7.4-apache

# Устанавливаем расширение mysqli для работы с MySQL
RUN docker-php-ext-install mysqli

# Копируем файлы проекта в директорию сервера Apache
COPY index.php /var/www/html/
COPY style.css /var/www/html/

# Указываем рабочую директорию
WORKDIR /var/www/html

# Открываем порт 80 для веб-сервера
EXPOSE 80